// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  /**
   * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
   */
  interface GetMessageOptions {
    /**
     * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
     */
    escapeLt?: boolean
  }

  export interface WxtI18n extends I18n.Static {
    /**
     * The extension or app ID; you might use this string to construct URLs for resources inside the extension. Even unlocalized extensions can use this message.
     * Note: You can't use this message in a manifest file.
     *
     * "<browser.runtime.id>"
     */
    getMessage(
      messageName: "@@extension_id",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "<browser.i18n.getUiLocale()>"
     */
    getMessage(
      messageName: "@@ui_locale",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * The text direction for the current locale, either "ltr" for left-to-right languages such as English or "rtl" for right-to-left languages such as Japanese.
     *
     * "<ltr|rtl>"
     */
    getMessage(
      messageName: "@@bidi_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "rtl"; otherwise, it's "ltr".
     *
     * "<rtl|ltr>"
     */
    getMessage(
      messageName: "@@bidi_reversed_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "left"; otherwise, it's "right".
     *
     * "<left|right>"
     */
    getMessage(
      messageName: "@@bidi_start_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "right"; otherwise, it's "left".
     *
     * "<right|left>"
     */
    getMessage(
      messageName: "@@bidi_end_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Extension name
     *
     * "Nikflix"
     */
    getMessage(
      messageName: "extensionName",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Extension description
     *
     * "Bypass the account-sharing restrictions"
     */
    getMessage(
      messageName: "extensionDescription",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Header title
     *
     * "🎬 Nikflix"
     */
    getMessage(
      messageName: "header",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Update notification message
     *
     * "🎉 New version available! Please update your extension."
     */
    getMessage(
      messageName: "updateAvailable",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * GitHub button
     *
     * "📂 Check code on GitHub"
     */
    getMessage(
      messageName: "checkCode",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Coffee button
     *
     * "☕ Buy me a coffee"
     */
    getMessage(
      messageName: "buyMeCoffee",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Bug report button
     *
     * "🐞 Report a bug"
     */
    getMessage(
      messageName: "reportBug",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Bug info hint text
     *
     * "If you have a bug, use the button with this icon in the controller. (or click here)"
     */
    getMessage(
      messageName: "bugInfoText",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Contact section label
     *
     * "Want to contact the developer?"
     */
    getMessage(
      messageName: "contactDeveloper",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Toggle label for the controller
     *
     * "Controller"
     */
    getMessage(
      messageName: "controllerLabel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Status text when toggle is on
     *
     * "Enable"
     */
    getMessage(
      messageName: "statusEnabled",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Status text when toggle is off
     *
     * "Disable"
     */
    getMessage(
      messageName: "statusDisabled",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Footer credit text
     *
     * "Made with ❤️ by"
     */
    getMessage(
      messageName: "madeWith",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Marquee contributors prefix
     *
     * "🙌 Thanks to Contributors :"
     */
    getMessage(
      messageName: "thanksContributors",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Update notification with version number
     *
     * "🎉 New version $VERSION$ available! Please update."
     */
    getMessage(
      messageName: "updateAvailableVersion",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    getMessage(
      messageName: "@@extension_id" | "@@ui_locale" | "@@bidi_dir" | "@@bidi_reversed_dir" | "@@bidi_start_edge" | "@@bidi_end_edge" | "extensionName" | "extensionDescription" | "header" | "updateAvailable" | "checkCode" | "buyMeCoffee" | "reportBug" | "bugInfoText" | "contactDeveloper" | "controllerLabel" | "statusEnabled" | "statusDisabled" | "madeWith" | "thanksContributors" | "updateAvailableVersion",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
  }
}
