// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  /**
   * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
   */
  interface GetMessageOptions {
    /**
     * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
     */
    escapeLt?: boolean
  }

  export interface WxtI18n extends I18n.Static {
    /**
     * The extension or app ID; you might use this string to construct URLs for resources inside the extension. Even unlocalized extensions can use this message.
     * Note: You can't use this message in a manifest file.
     *
     * "<browser.runtime.id>"
     */
    getMessage(
      messageName: "@@extension_id",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "<browser.i18n.getUiLocale()>"
     */
    getMessage(
      messageName: "@@ui_locale",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * The text direction for the current locale, either "ltr" for left-to-right languages such as English or "rtl" for right-to-left languages such as Japanese.
     *
     * "<ltr|rtl>"
     */
    getMessage(
      messageName: "@@bidi_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "rtl"; otherwise, it's "ltr".
     *
     * "<rtl|ltr>"
     */
    getMessage(
      messageName: "@@bidi_reversed_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "left"; otherwise, it's "right".
     *
     * "<left|right>"
     */
    getMessage(
      messageName: "@@bidi_start_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "right"; otherwise, it's "left".
     *
     * "<right|left>"
     */
    getMessage(
      messageName: "@@bidi_end_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Extension name
     *
     * "Nikflix"
     */
    getMessage(
      messageName: "extensionName",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Extension description
     *
     * "Bypass the account-sharing restrictions"
     */
    getMessage(
      messageName: "extensionDescription",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Header title
     *
     * "🎬 Nikflix"
     */
    getMessage(
      messageName: "header",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Update notification message
     *
     * "🎉 New version available! Please update your extension."
     */
    getMessage(
      messageName: "updateAvailable",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * GitHub button
     *
     * "📂 Check code on GitHub"
     */
    getMessage(
      messageName: "checkCode",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Coffee button
     *
     * "☕ Buy me a coffee"
     */
    getMessage(
      messageName: "buyMeCoffee",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Bug report button
     *
     * "🐞 Report a bug"
     */
    getMessage(
      messageName: "reportBug",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Bug info hint text
     *
     * "If you have a bug, use the button with this icon in the controller. (or click here)"
     */
    getMessage(
      messageName: "bugInfoText",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Contact section label
     *
     * "Want to contact the developer?"
     */
    getMessage(
      messageName: "contactDeveloper",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Toggle label for the controller
     *
     * "Controller"
     */
    getMessage(
      messageName: "controllerLabel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Status text when toggle is on
     *
     * "Enable"
     */
    getMessage(
      messageName: "statusEnabled",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Status text when toggle is off
     *
     * "Disable"
     */
    getMessage(
      messageName: "statusDisabled",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Footer credit text
     *
     * "Made with ❤️ by"
     */
    getMessage(
      messageName: "madeWith",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Marquee contributors prefix
     *
     * "🙌 Thanks to Contributors :"
     */
    getMessage(
      messageName: "thanksContributors",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Update notification with version number
     *
     * "🎉 New version $VERSION$ available! Please update."
     */
    getMessage(
      messageName: "updateAvailableVersion",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Onboarding subtitle
     *
     * "Welcome! Before you start, choose how you want to bypass the Netflix household restriction."
     */
    getMessage(
      messageName: "onboardingTitle",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Badge text
     *
     * "Recommended"
     */
    getMessage(
      messageName: "recommended",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * CSS block card title
     *
     * "CSS & DOM Block"
     */
    getMessage(
      messageName: "cssBlockTitle",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * CSS block card description
     *
     * "Hides and removes Netflix's restriction modal directly in your browser using CSS and DOM manipulation. The network request still completes normally — we simply make the modal invisible."
     */
    getMessage(
      messageName: "cssBlockDesc",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Legal status safe badge
     *
     * "✅ More Legal"
     */
    getMessage(
      messageName: "legalSafeBadge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Legal status safe description
     *
     * "Only modifies what is displayed, not what is sent over the network. The Netflix page works fully; we just hide the block screen. This is the safest approach legally."
     */
    getMessage(
      messageName: "legalSafeText",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * CSS block pro 1
     *
     * "⚡ Nikflix custom controller active"
     */
    getMessage(
      messageName: "cssPro1",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * CSS block pro 2
     *
     * "🎛️ Full playback controls"
     */
    getMessage(
      messageName: "cssPro2",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Tips button feature label
     *
     * "💡 Tips button included"
     */
    getMessage(
      messageName: "tipsIncluded",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * API block card title
     *
     * "API Block"
     */
    getMessage(
      messageName: "apiBlockTitle",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * API block card description
     *
     * "Completely blocks the GraphQL endpoint web.prod.cloud.netflix.com/graphql at the network level. The restriction check never reaches Netflix's servers."
     */
    getMessage(
      messageName: "apiBlockDesc",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Legal status warning badge
     *
     * "⚠️ More Radical"
     */
    getMessage(
      messageName: "legalWarnBadge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Legal status warning description
     *
     * "Intercepts and drops the network request entirely using the browser's declarativeNetRequest API. The restriction modal never loads."
     */
    getMessage(
      messageName: "legalWarnText",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * API block pro 1
     *
     * "🚫 Modal never loads"
     */
    getMessage(
      messageName: "apiPro1",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * API block pro 2
     *
     * "🎮 Netflix original controller"
     */
    getMessage(
      messageName: "apiPro2",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Confirm button text for CSS mode
     *
     * "Confirm — CSS & DOM Block"
     */
    getMessage(
      messageName: "confirmCssBtn",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Confirm button text for API mode
     *
     * "Confirm — API Block"
     */
    getMessage(
      messageName: "confirmApiBtn",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Confirmation note
     *
     * "You can always change this later in the extension popup."
     */
    getMessage(
      messageName: "confirmNote",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Mode section title
     *
     * "🔒 Blocking Mode"
     */
    getMessage(
      messageName: "blockingModeSection",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * CSS mode short description for popup
     *
     * "Hides the modal · Nikflix controller"
     */
    getMessage(
      messageName: "cssModeDescPopup",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * API mode short description for popup
     *
     * "Blocks GraphQL · Netflix controller"
     */
    getMessage(
      messageName: "apiModeDescPopup",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Badge shown on the currently playing episode in the episodes list
     *
     * "Playing"
     */
    getMessage(
      messageName: "nowPlaying",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Fallback label for a season without a title
     *
     * "Season $NUM$"
     */
    getMessage(
      messageName: "season",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the button that closes the episodes list
     *
     * "Close"
     */
    getMessage(
      messageName: "closeTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the controller's back button
     *
     * "Back"
     */
    getMessage(
      messageName: "backTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the tip/donation button
     *
     * "Support Nikflix ❤️"
     */
    getMessage(
      messageName: "supportNikflix",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the play button
     *
     * "Play (Space)"
     */
    getMessage(
      messageName: "playTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the pause button
     *
     * "Pause (Space)"
     */
    getMessage(
      messageName: "pauseTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the rewind button
     *
     * "Rewind 10 seconds (Left)"
     */
    getMessage(
      messageName: "rewindTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the forward button
     *
     * "Forward 10 seconds (Right)"
     */
    getMessage(
      messageName: "forwardTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the volume icon
     *
     * "Volume (M to mute)"
     */
    getMessage(
      messageName: "volumeTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the next-episode button
     *
     * "Next episode (N)"
     */
    getMessage(
      messageName: "nextEpisodeTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the episodes list button
     *
     * "Episodes and seasons"
     */
    getMessage(
      messageName: "episodesTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the audio and subtitles button
     *
     * "Audio and subtitles"
     */
    getMessage(
      messageName: "subtitlesTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the playback speed button
     *
     * "Playback speed: $SPEED$x"
     */
    getMessage(
      messageName: "speedTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Message shown when the playback speed changes
     *
     * "Speed: $SPEED$x"
     */
    getMessage(
      messageName: "speedMessage",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the autoplay button when enabled
     *
     * "Autoplay: ON"
     */
    getMessage(
      messageName: "autoplayTooltipOn",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the autoplay button when disabled
     *
     * "Autoplay: OFF"
     */
    getMessage(
      messageName: "autoplayTooltipOff",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Message shown when autoplay is enabled
     *
     * "Autoplay enabled"
     */
    getMessage(
      messageName: "autoplayMessageOn",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Message shown when autoplay is disabled
     *
     * "Autoplay disabled"
     */
    getMessage(
      messageName: "autoplayMessageOff",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Title of the fullscreen button
     *
     * "Fullscreen (F)"
     */
    getMessage(
      messageName: "fullscreenTooltip",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Text of the floating skip-intro button
     *
     * "Skip intro"
     */
    getMessage(
      messageName: "skipIntro",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Text of the floating skip-outro/next-episode button
     *
     * "Next episode"
     */
    getMessage(
      messageName: "nextEpisodeLabel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Message shown after skipping the intro
     *
     * "Intro skipped"
     */
    getMessage(
      messageName: "introSkippedMessage",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Message shown just before autoplaying the next episode
     *
     * "Playing next episode..."
     */
    getMessage(
      messageName: "nextEpisodePlayingMessage",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Message shown when rewinding 10 seconds
     *
     * "-10 sec"
     */
    getMessage(
      messageName: "rewindMessage",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Message shown when fast-forwarding 10 seconds
     *
     * "+10 sec"
     */
    getMessage(
      messageName: "forwardMessage",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    getMessage(
      messageName: "@@extension_id" | "@@ui_locale" | "@@bidi_dir" | "@@bidi_reversed_dir" | "@@bidi_start_edge" | "@@bidi_end_edge" | "extensionName" | "extensionDescription" | "header" | "updateAvailable" | "checkCode" | "buyMeCoffee" | "reportBug" | "bugInfoText" | "contactDeveloper" | "controllerLabel" | "statusEnabled" | "statusDisabled" | "madeWith" | "thanksContributors" | "updateAvailableVersion" | "onboardingTitle" | "recommended" | "cssBlockTitle" | "cssBlockDesc" | "legalSafeBadge" | "legalSafeText" | "cssPro1" | "cssPro2" | "tipsIncluded" | "apiBlockTitle" | "apiBlockDesc" | "legalWarnBadge" | "legalWarnText" | "apiPro1" | "apiPro2" | "confirmCssBtn" | "confirmApiBtn" | "confirmNote" | "blockingModeSection" | "cssModeDescPopup" | "apiModeDescPopup" | "nowPlaying" | "season" | "closeTooltip" | "backTooltip" | "supportNikflix" | "playTooltip" | "pauseTooltip" | "rewindTooltip" | "forwardTooltip" | "volumeTooltip" | "nextEpisodeTooltip" | "episodesTooltip" | "subtitlesTooltip" | "speedTooltip" | "speedMessage" | "autoplayTooltipOn" | "autoplayTooltipOff" | "autoplayMessageOn" | "autoplayMessageOff" | "fullscreenTooltip" | "skipIntro" | "nextEpisodeLabel" | "introSkippedMessage" | "nextEpisodePlayingMessage" | "rewindMessage" | "forwardMessage",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
  }
}
