// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/_locales/ar/messages.json"
    | "/_locales/en/messages.json"
    | "/_locales/es/messages.json"
    | "/_locales/fr/messages.json"
    | "/_locales/pt/messages.json"
    | "/content-scripts/content.js"
    | "/icons/Nikflix-48.png"
    | "/icons/Nikflix-48OFF.ico"
    | "/icons/Nikflix-64.png"
    | "/netflix-audioChange.js"
    | "/netflix-seeker.js"
    | "/netflix-substitleChange.js"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
